M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date Mi 06 Dez 2023 10:13:35 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-06T10:13:35+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X20.185Y22.36
T0
M30
