# Set the Target build dirs
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

BINDIR_DEBUG     = $(ROOTDIR)/bin/Debug
BINDIR_RELEASE   = $(ROOTDIR)/bin/Release
WBINDIR_DEBUG    = $(subst /,\,$(BINDIR_DEBUG))
WBINDIR_RELEASE  = $(subst /,\,$(BINDIR_RELEASE))

BUILDDIR_DEBUG   = $(ROOTDIR)/build/$(TARGET)/Debug/
BUILDDIR_RELEASE = $(ROOTDIR)/build/$(TARGET)/Release/
WBUILDDIR_DEBUG  = $(subst /,\,$(BUILDDIR_DEBUG))
WBUILDDIR_RELEASE = $(subst /,\,$(BUILDDIR_RELEASE))

SRCDIR           = $(ROOTDIR)/src

ELFFILE_DEBUG    = $(BINDIR_DEBUG)/$(TARGET).elf
ELFFILE_RELEASE  = $(BINDIR_RELEASE)/$(TARGET).elf

MAPFILE_DEBUG    = $(BINDIR_DEBUG)/$(TARGET).map
MAPFILE_RELEASE  = $(BINDIR_RELEASE)/$(TARGET).map

HEXFILE_DEBUG    = $(BINDIR_DEBUG)/$(TARGET).hex
HEXFILE_RELEASE  = $(BINDIR_RELEASE)/$(TARGET).hex
WHEXFILE_DEBUG   = $(subst /,\,$(HEXFILE_DEBUG))
WHEXFILE_RELEASE = $(subst /,\,$(HEXFILE_RELEASE))

LSSFILE_DEBUG    = $(BINDIR_DEBUG)/$(TARGET).lss
LSSFILE_RELEASE  = $(BINDIR_RELEASE)/$(TARGET).lss

SYMFILE_DEBUG    = $(BINDIR_DEBUG)/$(TARGET).sym
SYMFILE_RELEASE  = $(BINDIR_RELEASE)/$(TARGET).sym

EEPFILE_DEBUG    = $(BINDIR_DEBUG)/$(TARGET).eep
EEPFILE_RELEASE  = $(BINDIR_RELEASE)/$(TARGET).eep

# Log file targets and dirs
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

LOGDIR_DEBUG     = $(BUILDDIR_DEBUG)
LOGFILE_DEBUG    = $(LOGDIR_DEBUG)/$(TARGET).log

LOGDIR_RELEASE   = $(BUILDDIR_RELEASE)
LOGFILE_RELEASE  = $(LOGDIR_RELEASE)/$(TARGET).log
