# =========================================================================
# Makefile

# =========================================================================

:first debug

include lib/mod_build.mk
include lib/mod_clean.mk
#include $(NIGHTLY_LIB)/mod_doygen.mk

# =========================================================================

help:
	@echo ""
	@echo "    helpbuild   - lists build targets"
	@echo "    helpclean   - lists cleaning targets"

helpall: helpbuild helpclean

.PHONY: help helpall

